### ISSUE TITLE
multiply instance on one page support 

### ISSUE THREAD

**Issue by juliycesar** [wildcard/ReCaptcha-ASP.NET-MVC#11]
as I undersnad multyply instances of captcha on one page  is not supported currently ?

**Comment by wildcard** [comment]
I'll check that :)

**Comment by wildcard** [comment]
I will deploy a version adding this feature

**Comment by wildcard** [comment]
@juliycesar I'm going to implement it by this https://developers.google.com/recaptcha/docs/display?hl=en#example look at the _Explicit rendering for multiple widgets_
