### ISSUE TITLE
Add readme to open on nuget installation 

### ISSUE THREAD

**Issue by wildcard** [wildcard/ReCaptcha-ASP.NET-MVC#12]
https://docs.nuget.org/create/creating-and-publishing-a-package#user-content-automatically-displaying-a-readmetxt-file-during-package-installation

**Comment by saurabhrajguru** [comment]
What should be the content of readme file ?

**Comment by wildcard** [comment]
Open the repository readme file or copy the usage instructions from the readme

**Comment by wildcard** [comment]
@saurabhrajguru 10x
