### ISSUE TITLE
Greater clarity in the read me for beginners?

### ISSUE THREAD

**Issue by xand7** [wildcard/ReCaptcha-ASP.NET-MVC#14]
Hello,

I am a beginner using MVC and trying to get your package to work, however when I add:

@ReCaptcha.GetHtml(@ViewBag.publickey)

to my form view I have the issue 'The name ReCaptcha does not exist in the current context'.  I presume this is because I need to add a '@using' of some sort to the top of the page, I can't seem to determine what though.  Whilst it might seem like a minor thing to someone who knows what they are doing, for a beginner like me it would be very useful if the read me page explained exactly what should be added to the page so that I do not receive the above error.

Thanks for your time.

**Comment by wildcard** [comment]
Please look at Microsoft post how to use their (it's pretty similar)

If I not wrong, You have to add using to the assembly of the nuget.

I believe 'using reCaptcha' will suffice.

Thanks for reaching me :)

**Comment by wildcard** [comment]
@xand7 I created a pull request #16
I'll appreciate if you take the time to review it

Thanks

**Comment by xand7** [comment]
Thanks for adding that.

**Comment by wildcard** [comment]
Thanks for using my Helper ^_^
