### ISSUE TITLE
Recaptcha for login to prevent bruteforce

### ISSUE THREAD

**Issue by papyr** [wildcard/ReCaptcha-ASP.NET-MVC#17]
Hello, I like the wrapper :+1:  need some help integrating with Login Form (not just register).

For it to work, I understand that the recaptcha needs to call google validation service, but when user clicks submit, its posting back to my server - so how can I get the correct validation. Or, is this auto handled?

What do I need to do to ensure the validation service will work in the login form?
Do I need to catch/wrap and route the google recaptcha check?

thanks

**Comment by wildcard** [comment]
Thanks for using the wrapper :)

Login and register should be handled pretty similarly.

When you use reCaptcha (put Google script on the page) the recaptcha control is rendered on the page, the control communicate with Google servers automatically.

The only thing you left to do on your side is validating with Google the user response on server side.
The wrapper provide a call for that.

I hope I assisted you ^_^

**Comment by papyr** [comment]
Thanks so much for the response.

One more question, when I check google help page for ASP, it says V2 for recaptcha. On the google page, it recommends including _API_ script, can you tell me which scripts I should use, and which will ones I do not have to worry about the version conflicts

https://developers.google.com/recaptcha/docs/faq#can-i-customize-the-recaptcha-widget
![untitled](https://cloud.githubusercontent.com/assets/12733414/16364304/9dbd9cf6-3bb1-11e6-8071-272177972cbd.png)

**Comment by wildcard** [comment]
ReCaptcha V2 Google took a different approach, they didn't supply an SDK.
They instruct the users to include their script straight without any library.

This wrapper do all the work for you, with a simple interface allows you to use reCaptcha.

If you want to use Google instructions you can go head. there is no necessary need to use this wrapper, it exists only for your convince 😊

**Comment by papyr** [comment]
Hi, can you please tell me which section of the web.config would I add the recaptcha

**Comment by wildcard** [comment]
You don't have to configure in the web.config (it is just for your convenience).

If you choose to configure the keys like it's suggested by the Readme, you need to configure the keys in the `<appsetting>` section.

Look at the link below 
https://msdn.microsoft.com/en-us/library/aa903313(v=vs.71).aspx
