### ISSUE TITLE
multiple captchas on page and widget IDs

### ISSUE THREAD

**Issue by mustafaarun** [wildcard/ReCaptcha-ASP.NET-MVC#18]
Hello,

as a result of using multiple captchas on a page i use GetExplictHtml method but is it possible to get the created widget id to use as parameter when validating captcha via js by grecaptcha.getresponse method ?

thank you

**Comment by wildcard** [comment]
fixed on version [`1.2.3`](https://www.nuget.org/packages/reCaptcha.AspNet.Mvc/1.2.3)
closing 💯
