### ISSUE TITLE
Language Settings for ReCaptcha

### ISSUE THREAD

**Issue by dnxit** [wildcard/ReCaptcha-ASP.NET-MVC#5]
how to set Language it always show text in arabic may be due to UAE IP or I don't know the reason kindly advise

**Comment by wildcard** [comment]
Will fix this

**Comment by wildcard** [comment]
By default the language is auto detected, I'll add the option to specify language.

**Comment by wildcard** [comment]
@afzalgujrat please update your nuget to 1.1.1 it's now including your request :)

**Comment by dnxit** [comment]
Thanks man :) :+1:
