### ISSUE TITLE
NuGet package needs a dependency on RazorGenerator.Mvc

### ISSUE THREAD

**Issue by krillgar** [wildcard/ReCaptcha-ASP.NET-MVC#9]
I tried using this NuGet package for the first time today in an Identity Server MVC5 application. I would think that RazorGenerator.Mvc could easily be one of those packages assumed to be in every web project, but after installing your package, my project immediately started throwing Yellow Screens: "Could not load file or assembly 'RazorGenerator.Mvc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=7b26dc2a43f6a0d4' or one of its dependencies. The system cannot find the file specified."

I tried uninstalling, rolling back my checkouts, and reinstalling, and received the same issue. If I download that package from NuGet separately, it immediately begins to work again.

**Comment by wildcard** [comment]
I'll look into this problem, I use razor generator to precomplie the razor - I shouldn't impose razor generator on you or any user.
Thanks for the issue

**Comment by wildcard** [comment]
Dear @krillgar please check if version 1.1.3 is helping you :)

**Comment by krillgar** [comment]
Works great with 1.1.3. Thanks so much!

(Especially the comment about "I shouldn't impose that on you or any user". Love the SoC mindset.)

**Comment by wildcard** [comment]
Happy to help! friend :+1:
